//
//  DetailPresenter.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailPresenter {

    // MARK: - Private properties -

    private unowned let view: DetailViewInterface
    private let formatter: DetailFormatterInterface
    private let interactor: DetailInteractorInterface
    private let wireframe: DetailWireframeInterface
    
    private let wireFrameData: DetailWireframeData!

    // MARK: - Lifecycle -

    init(view: DetailViewInterface, formatter: DetailFormatterInterface, interactor: DetailInteractorInterface, wireframe: DetailWireframeInterface, data: DetailWireframeData) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
        self.wireFrameData = data
    }
}

// MARK: - Extensions -
extension DetailPresenter: DetailPresenterInterface {
    
    func getProductViewComponentData() -> ProductViewComponentData {
        return wireFrameData.productData.setImageHeight(with: 300)
    }
    
}
