//
//  DetailWireframe.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Detail", bundle: nil)

    // MARK: - Module setup -

    init(data: DetailWireframeData) {
        let moduleViewController = storyboard.instantiateViewController(ofType: DetailViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = DetailFormatter()
        let interactor = DetailInteractor()
        let presenter = DetailPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self, data: data)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailWireframe: DetailWireframeInterface {
}
