//
//  DetailInteractor.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailInteractor {
    
    private var factory = CartOperationsFactoryManager()
    
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
    
    func getProductDetailResponse(callBack: ProductDetailCallBack, params: ProductDetailRequest) {
        factory.createProductDetailUseCase().execute(useCaseCallBack: callBack, params: params)
    }
    
}
