//
//  MainViewController.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainViewController: UIViewController {

    private let takasi = CartListUseCase()
    private let callBack = CardListCallBack()

    // MARK: - Public properties -

    var presenter: MainPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .red
        
        callBack.commonResult { [weak self](result) in
            switch result {
            case .failure(let error):
                print("error : \(error)")
            case .success(let data):
                print("data : \(data.products)")
            }
        }
        
        takasi.execute(useCaseCallBack: callBack, params: CartListRequest())
        
    }

}

// MARK: - Extensions -

extension MainViewController: MainViewInterface {
}
