//
//  MainPresenter.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainPresenter {

    // MARK: - Private properties -

    private unowned let view: MainViewInterface
    private let formatter: MainFormatterInterface
    private let interactor: MainInteractorInterface
    private let wireframe: MainWireframeInterface
    
    private var callBack = CartListCallBack()

    // MARK: - Lifecycle -

    init(view: MainViewInterface, formatter: MainFormatterInterface, interactor: MainInteractorInterface, wireframe: MainWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    private func getCartList() {
        callBack.commonResult(completion: cartListResponseListener)
        interactor.getCartListData(parameters: CartListRequest(), callBack: callBack)
    }
    
    private lazy var cartListResponseListener: (Result<CartListResponse, ErrorResponse>) -> Void = { [weak self] result in
        self?.handleCartListResponse(with: result)
    }
    
    private func handleCartListResponse(with result: Result<CartListResponse, ErrorResponse>) {
        switch result {
        case .failure(let error):
            print("cartList error : \(error)")
        case .success(let data):
            print("cartList data : \(data)")
        }
    }
    
}

// MARK: - Extensions -

extension MainPresenter: MainPresenterInterface {
    
    func viewDidLoad() {
        getCartList()
    }
    
}
