//
//  MainViewController.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainViewController: UIViewController {

    // MARK: - Public properties -
    var presenter: MainPresenterInterface!

    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .red

        presenter.viewDidLoad()
        
    }

}

// MARK: - Extensions -
extension MainViewController: MainViewInterface {
}
