//
//  MainFormatter.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainFormatter {
    
    private var cartListResponse: CartListResponse?
    private var productViewComponentData = Array<GenericDataProtocol>()
    
    private func cartListComponentMapper() {

        guard let response = cartListResponse, let data = response.products else { return }
        
        productViewComponentData.removeAll()
        
        productViewComponentData = data.map { (product) -> ProductViewComponentData in
            
            return ProductViewComponentData(productId: product.productID, imageData: CustomImageViewComponentData(imageUrl: product.image ?? ""), productInfoData: ProductBottomInfoComponentData(productNameData: ProductNameLabelData(name: product.name ?? ""), productPriceData: PriceInfoLabelData(price: product.price ?? 0.0)))
            
        }
        
    }
    
}

// MARK: - Extensions -

extension MainFormatter: MainFormatterInterface {
    
    func setData(with response: CartListResponse) {
        self.cartListResponse = response
        cartListComponentMapper()
    }
    
    func returnNumberOfSection() -> Int {
        return 1
    }
    
    func returnNumberOfItems(in section: Int) -> Int {
        return productViewComponentData.count
    }
    
    func returnWidgetComponentItem(index: Int) -> GenericDataProtocol? {
        return productViewComponentData[index]
    }
    
    
    
    
}
