//
//  MainInteractor.swift
//  CartCodeCase
//
//  Created by Erkut Bas on 20.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MainInteractor {
    
    private var cartListFactory = CartListFactoryManager()
    
}

// MARK: - Extensions -

extension MainInteractor: MainInteractorInterface {
    
    func getCartListData(parameters: CartListRequest, callBack: CartListCallBack) {
        cartListFactory.createCartListUseCase().execute(useCaseCallBack: callBack, params: parameters)
    }

    func saveToCoreData(data: Array<Product>) {
        cartListFactory.createCartListSaveUseCase().execute(params: data)
    }
    
}
